# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-16 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_in', models.CharField(max_length=200)),
                ('left_out', models.CharField(max_length=200)),
                ('right_out', models.CharField(max_length=200)),
            ],
        ),
    ]
