# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 23:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamegames', '0003_auto_20171013_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('requires', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('sets', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('removes', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('adds', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('insert_into', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='archetype',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamegames.Game'),
        ),
    ]
