# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 17:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamegames', '0005_auto_20171019_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='for_players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=[True, True], size=None),
        ),
    ]
