# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 23:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamegames', '0008_game_game_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='insert_into',
        ),
        migrations.AlterField(
            model_name='game',
            name='archetype',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='fields_to_display',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_ai',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='how_to_play',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_game_over',
            field=models.IntegerField(choices=[(2, 'DEFEAT'), (3, 'DRAW'), (1, 'VICTORY'), (0, 'GAME CONTINUES')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='turn_order',
            field=models.IntegerField(choices=[(1, 'SIMULTANEOUS'), (0, 'SEQUENTIAL')]),
        ),
        migrations.AlterField(
            model_name='move',
            name='requires',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
