# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 00:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamegames', '0009_auto_20171020_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_game_over',
            field=models.IntegerField(choices=[(2, 'DEFEAT'), (0, 'GAME CONTINUES'), (3, 'DRAW'), (1, 'VICTORY')]),
        ),
        migrations.AlterField(
            model_name='move',
            name='adds',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='move',
            name='removes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='move',
            name='requires',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='move',
            name='sets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
    ]
